Repository EC-Release/oci, pull requests merged in 2020-07, with the labels that each got.

#19 Deployment scripts for EC gateway and load balancer
  .github/workflows/terraform.yml
  .gitignore
  spec/loadbalancer/terraform/README.md
  spec/loadbalancer/terraform/example-tfvars/terraform.tfvars
  spec/loadbalancer/terraform/integration-tests/go.mod
  spec/loadbalancer/terraform/integration-tests/go.sum
  spec/loadbalancer/terraform/integration-tests/integration_test.go
  spec/loadbalancer/terraform/main.tf
  spec/loadbalancer/terraform/variables.tf
Labels: documentation, enhancement, spec, template

#40 V1.1beta helm pkg update
  k8s/agent/templates/deployment.yaml
  k8s/example/ec.env
  k8s/example/values.yaml
Labels: bug, documentation, enhancement, example, spec, template

#41 fix a duplicate image field
  k8s/agent/templates/deployment.yaml
Labels: bug, spec

#42 add spec building to travis
  .travis.yml
Labels: build, enhancement, spec

#43 add build badge
  README.md
Labels: spec

#44 update versioning usage in readme.
  k8s/README.md
Labels: documentation, example

#45 - update img pullpolicy to always to prevent cached outdated pkg
  k8s/agent+tls/values.yaml
  k8s/agent+vln/values.yaml
  k8s/agent/values.yaml
Labels: enhancement, spec

#46 V1 oci spec update
  .travis.yml
  spec/agent/Dockerfile
Labels: build, enhancement, example, spec, template

#47 Update Dockerfile
  spec/agent/Dockerfile
Labels: good first issue, spec

#48 fix docker push issue
  .travis.yml
Labels: bug, build, enhancement

#49 Update .travis.yml
  .travis.yml
Labels: bug, build

#50 update cleanup usage
  .travis.yml
Labels: bug, build

#51 Update .travis.yml
  .travis.yml
Labels: bug, build

#52 Update .travis.yml
  .travis.yml
Labels: bug, build

#53 add chart customisation options.
  k8s/README.md
Labels: documentation

#54 V1.1beta helm pkg update
  k8s/agent/templates/_helpers.tpl
  k8s/agent/templates/deployment.yaml
  k8s/example/values.yaml
Labels: enhancement, example, spec, template

#55 Update Dockerfile
  spec/agent/Dockerfile
Labels: bug, enhancement, spec

#56 V1 oci spec update
  spec/agent/Dockerfile
  spec/agent/agent.sh
  spec/agent/client.yml
  spec/agent/gateway.yml
  spec/agent/gw:client.yml
  spec/agent/gw:server.yml
  spec/agent/server.yml
Labels: spec

#60 V1.1beta helm pkg update
  k8s/agent/templates/_helpers.tpl
  k8s/example/ec.env
Labels: bug, enhancement, spec, template

#61 V1.1beta helm pkg update
  k8s/README.md
  k8s/agent/templates/_helpers.tpl
  k8s/agent/templates/deployment.yaml
  k8s/example/values.yaml
Labels: enhancement, spec, template

#65 V1.1beta helm pkg update
  .travis.yml
  k8s/README.md
  k8s/agent/templates/deployment.yaml
  k8s/example/values.yaml
Labels: enhancement, spec

#69 Update .travis.yml
  .travis.yml
Labels: documentation, enhancement
